CREATE SCHEMA IF NOT EXISTS AMS_LOG;

CREATE TABLE IF NOT EXISTS AMS_HODS_LOG (
    CREATED    VARCHAR(15) UTF8,
    LOAD_DTS   TIMESTAMP,
    LOG_LEVEL  VARCHAR(16) UTF8,
    MESSAGE    VARCHAR(4000) UTF8,
    FUNC_NAME  VARCHAR(64) UTF8,
    PARAMS     VARCHAR(64) UTF8,
    DB_OBJECT  VARCHAR(64) UTF8,
    QUERY      VARCHAR(2000000) UTF8,
    ROWS_COUNT DECIMAL(18,0),
    DURATION   DECIMAL(18,0),
    ERROR_CODE DECIMAL(18,0)
);

CREATE TABLE IF NOT EXISTS AMS_DFJR_LOG (
    CREATED    VARCHAR(15) UTF8,
    LOAD_DTS   TIMESTAMP,
    LOG_LEVEL  VARCHAR(16) UTF8,
    MESSAGE    VARCHAR(4000) UTF8,
    FUNC_NAME  VARCHAR(64) UTF8,
    PARAMS     VARCHAR(64) UTF8,
    DB_OBJECT  VARCHAR(64) UTF8,
    QUERY      VARCHAR(2000000) UTF8,
    ROWS_COUNT DECIMAL(18,0),
    DURATION   DECIMAL(18,0),
    ERROR_CODE DECIMAL(18,0)
);

CREATE TABLE IF NOT EXISTS AMS_DICT_LOG (
    CREATED    VARCHAR(15) UTF8,
    LOAD_DTS   TIMESTAMP,
    LOG_LEVEL  VARCHAR(16) UTF8,
    MESSAGE    VARCHAR(4000) UTF8,
    FUNC_NAME  VARCHAR(64) UTF8,
    PARAMS     VARCHAR(64) UTF8,
    DB_OBJECT  VARCHAR(64) UTF8,
    QUERY      VARCHAR(2000000) UTF8,
    ROWS_COUNT DECIMAL(18,0),
    DURATION   DECIMAL(18,0),
    ERROR_CODE DECIMAL(18,0)
);

CREATE TABLE IF NOT EXISTS AMS_LHODS_LOG (
    CREATED    VARCHAR(15) UTF8,
    LOAD_DTS   TIMESTAMP,
    LOG_LEVEL  VARCHAR(16) UTF8,
    MESSAGE    VARCHAR(4000) UTF8,
    FUNC_NAME  VARCHAR(64) UTF8,
    PARAMS     VARCHAR(64) UTF8,
    DB_OBJECT  VARCHAR(64) UTF8,
    QUERY      VARCHAR(2000000) UTF8,
    ROWS_COUNT DECIMAL(18,0),
    DURATION   DECIMAL(18,0),
    ERROR_CODE DECIMAL(18,0)
);

CREATE TABLE IF NOT EXISTS AMS_LOGS (
    PROCESS       VARCHAR(100) UTF8,
    USER_NAME     VARCHAR(15) UTF8,
    LOAD_DTS      TIMESTAMP,
    FUNC_NAME     VARCHAR(64) UTF8,
    DURATION      DECIMAL(18,3),
    MESSAGE       VARCHAR(4000) UTF8,
    ERROR_CODE    DECIMAL(18,0),
    LOG_LEVEL     VARCHAR(16) UTF8,
    AFFECTED_ROWS DECIMAL(18,0),
    QUERY         VARCHAR(2000000) UTF8
);

CREATE TABLE IF NOT EXISTS AMS_LOGS_BUFFER (
    PROCESS       VARCHAR(100) UTF8,
    USER_NAME     VARCHAR(15) UTF8,
    LOAD_DTS      TIMESTAMP,
    FUNC_NAME     VARCHAR(64) UTF8,
    DURATION      DECIMAL(18,3),
    MESSAGE       VARCHAR(4000) UTF8,
    ERROR_CODE    DECIMAL(18,0),
    LOG_LEVEL     VARCHAR(16) UTF8,
    AFFECTED_ROWS DECIMAL(18,0),
    QUERY         VARCHAR(2000000) UTF8
);


